# 1. 넘파이(numpy)

넘파이(Numpy)는 파이썬에서 사용되는 과학 및 수학 연산을 위한 강력한 라이브러리입니다. 주로 다차원 배열을 다루는 데에 특화되어 있어, 데이터 분석, 머신러닝, 과학 계산 등 다양한 분야에서 널리 사용됩니다. 넘파이 배열은 C 언어로 구현되어 있어 연산이 빠르고 효율적입니다. 특히 큰 데이터셋에서 수치 연산을 수행할 때 뛰어난 성능을 보입니다. 또한 메모리 사용을 최적화하고 효율적으로 관리합니다.

In [ ]:
!pip install numpy

# 2. 넘파이의 주요 특징과 기능

### 2-1. 다차원 배열(N-dimensional array)
넘파이의 핵심은 다차원 배열인 ndarray입니다. 이 배열은 동일한 자료형을 가지는 원소들로 이루어져 있습니다. 다차원 배열은 1차원, 2차원, 3차원 등 다양한 차원을 가질 수 있습니다.

In [ ]:
# 리스트
list1 = [1,2,3,4]
list2 = [[1,2,3,4],[5,6,7,8]]
print(list1)
print(list2)
print(type(list1))
print(type(list1[0]))
print(type(list2[0]))

[1, 2, 3, 4]
[[1, 2, 3, 4], [5, 6, 7, 8]]
<class 'list'>
<class 'int'>
<class 'list'>


In [ ]:
import numpy as np

#ndarray
#1차원 배열
ndarr1 = np.array([1,2,3,4])
print(ndarr1) # 출력할때 ndarray는 list와 유사하지만 ,콤마 가 없다
print(type(ndarr1))
print(type(ndarr1[1]))

[1 2 3 4]
<class 'numpy.ndarray'>
<class 'numpy.int64'>


In [ ]:
#2차원 배열
ndarr2 = np.array([[1,2,3],[4,5,6]]) # 리스트를 넣어줌
print(ndarr2)
print(type(ndarr2[0]))

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


### 2-2. 리스트와 ndarray 변환

데이터 타입을 다른 데이터 타입으로 변환할 수 있습니다. 리스트에서 배열로의 변환은 np.array() 함수를 사용하고, 배열에서 리스트로의 변환은 tolist() 메서드를 사용합니다.

In [ ]:
# 리스트를 ndarray로 변환
list1 = [1,2,3,4]
ndarr1 = np.array(list1)
print(ndarr1)
print(type(ndarr1))

# ndarray를 리스트로 변환
list2 = ndarr1.tolist()
print(list2)
print(type(list2))

[1 2 3 4]
<class 'numpy.ndarray'>
[1, 2, 3, 4]
<class 'list'>


### 2-3. ndarray의 데이터 타입
넘파이의 ndarray는 동일한 자료형을 가지는 원소들로 이루어져 있으며, 다양한 데이터 타입을 지원합니다.

In [ ]:
list1 = [1, 3.14, 'Python', '🤠', True]
print(list1)
print(list1[3])

[1, 3.14, 'Python', '🤠', True]
🤠


In [ ]:
# ndarray
ndarr1 = np.array([1,2,3,4])
print(ndarr1)
ndarr2 = np.array([1,2,3.14,4])
print(ndarr2) # .찍히면서 전부다 실수형으로 바뀜
ndarr3 = np.array([1,2,3.14,True])
print(ndarr3) # True가 1로 바뀜
ndarr4 = np.array(['1',2,3.14,True])
print(ndarr4) # 다 문자열로 되어버림  순서불린 < 정수 < 실수 < 문자열

[1 2 3 4]
[1.   2.   3.14 4.  ]
[1.   2.   3.14 1.  ]
['1' '2' '3.14' 'True']


In [ ]:
ndarr3 = np.array([1,2,3.14,True], dtype = int)
print(ndarr3)
ndarr4 = np.array(['1',2,3.14,True], dtype=int) # True는 숫자가 아니기 때문에 에러발생
  print(ndarr4)
#ndarr4 = np.array(['1',2,3.14,'True'], dtype=int) # True는 숫자가 아니기 때문에 에러발생
#print(ndarr4)

[1 2 3 1]
[1 2 3 1]


### 2-4. ndarray 인덱싱과 슬라이싱
넘파이의 ndarray는 리스트와 유사하게 인덱싱과 슬라이싱을 지원합니다.

In [ ]:
ndarr1 = np.array(['🍇','🍈','🍉','🍊','🍋'])
print(ndarr1)
print(ndarr1.shape) # 5개의 데이터를 숫자 / 세트 형태로 반환하기때문에 뒤에 ,

['🍇' '🍈' '🍉' '🍊' '🍋']
(5,)


In [ ]:
# 인덱싱
print(ndarr1[0])
print(ndarr1[4])
print(ndarr1[-1])
print(ndarr1[-2])

🍇
🍋
🍋
🍊


In [ ]:
# 슬라이싱
# '🍇','🍈','🍉','🍊','🍋'
print(ndarr1[0:3])
print(ndarr1[2:])
print(ndarr1[:3])

['🍇' '🍈' '🍉']
['🍉' '🍊' '🍋']
['🍇' '🍈' '🍉']


In [ ]:
ndarr2d = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]]) # 2차원이기 때문에 대괄호가 두개!
print(ndarr2d)
print(ndarr2d.shape) # 행렬로 내보내줌 (row, columns) / (행,열)

print(ndarr2d[0,2])
print(ndarr2d[0][2]) # 밑 형식을 더 많이 사용함(행/열)을 슬라이싱

# 0행 가져오기
print(ndarr2d[0])
print(ndarr2d[0,])
print(ndarr2d[0,:]) # :은 모든이라고 볼 수 있다 -> 모든 열을 가져온다

# 0열 가져오기
print(ndarr2d[:, 0]) # :을 써야만 가능 [,0]방법은 에러남

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
3
3
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 5 9]


### 2-5. Fancy Indexing

Fancy indexing은 넘파이에서 배열을 인덱싱하는 강력하고 유연한 방법 중 하나입니다. Fancy indexing은 정수 배열이나 불리언 배열을 사용하여 배열의 일부를 선택하는 방법을 말합니다. 이를 통해 여러 개의 요소를 한 번에 선택하거나 조건에 맞게 선택할 수 있습니다.

In [ ]:
ndarr1 = np.array([10,15,2,8,20,90,85,44,23,32])
print(ndarr1)
idx = [2,5,9]
print(ndarr1[idx])

[10 15  2  8 20 90 85 44 23 32]
[ 2 90 32]


In [ ]:
ndarr2d = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])

print(ndarr2d[[0, 1], :])

[[1 2 3 4]
 [5 6 7 8]]


### 2-6. Boolean Indexing
Boolean Indexing은 넘파이에서 배열의 원소를 선택하는 강력하고 유용한 방법 중 하나입니다. 이 방법은 불리언(Boolean) 값으로 이루어진 배열을 사용하여 조건을 충족하는 원소만 선택하는 방식입니다.

In [ ]:
ndarr1 = np.array(['🍇','🍈','🍉','🍊','🍋'])
selValue = [True, False, True, True, False]
print(ndarr1[selValue])

selValue = [True, False, True]
# print(ndarr1[selValue]) 갯수가 안 맞아서 오류남

['🍇' '🍉' '🍊']


In [ ]:
ndarr2d = np.array([[1,2,3,4],
                    [5,6,7,8],
                    [9,10,11,12]])
print(ndarr2d > 7)
print(ndarr2d[ndarr2d>7]) # 조건에 맞는 결과값만 반환가능

[[False False False False]
 [False False False  True]
 [ True  True  True  True]]
[ 8  9 10 11 12]


# 3. 행렬 연산
넘파이에서는 다차원 배열인 ndarray를 사용하여 행렬 연산을 수행할 수 있습니다. 행렬 연산은 선형 대수와 관련이 깊어, 데이터 과학, 머신러닝, 통계 등 다양한 분야에서 사용됩니다.

In [ ]:
a = np.array([[1,2,3],
              [2,3,4]])

b = np.array([[3,4,5],
              [1,2,3]])

print(a.shape, b.shape)

(2, 3) (2, 3)


In [ ]:
# 행렬 덧셈
print(a+3)
print(a+b)

# 행렬 뺄셈
print(a-3)
print(a-b)

# 행렬 원소별 곱셈
print(a*3)
print(a*b)

# 행렬 곱(Dot product)
# a @ b
# np.dot(a,b)
# 행렬 곱 조건 : 맞닿는 shape가 같아야함. 떨어져있는 shape가 결과행렬이 됌
c = np.array([[1,2,3],
              [1,2,3],
              [2,3,4]])
d = np.array([[1,2],
              [3,4],
              [5,6]])
print(c.shape, d.shape) # (3, 3) (3, 2) / 결과는 (3,2)로 나옴

# 행렬 나눗셈
print(a / b)

[[4 5 6]
 [5 6 7]]
[[4 6 8]
 [3 5 7]]
[[-2 -1  0]
 [-1  0  1]]
[[-2 -2 -2]
 [ 1  1  1]]
[[ 3  6  9]
 [ 6  9 12]]
[[ 3  8 15]
 [ 2  6 12]]
(3, 3) (3, 2)
[[0.33333333 0.5        0.6       ]
 [2.         1.5        1.33333333]]


In [ ]:
print((1*1 + 2*3 + 3*5),(1*2 + 2*4 + 3*6))
print((1*1 + 2*3 + 3*5),(1*2 + 2*4 + 3*6))
print((2*3 + 3*3 + 4*5),(2*2 + 3*4 + 4*6))

22 28
22 28
35 40


In [ ]:
print(c@d)
print(np.dot(c,d))

[[22 28]
 [22 28]
 [31 40]]
[[22 28]
 [22 28]
 [31 40]]


In [ ]:
# 전치 행렬 : 행과 열을 바꿈
print(a)
print(a.T)

[[1 2 3]
 [2 3 4]]
[[1 2]
 [2 3]
 [3 4]]


In [ ]:
# 역행렬
# 정사각행렬(행과 열의 개수가 같은 경우)
# A = [[a b], [c,d]] => ad - bc != 0
# AA-1 = A-1A = |(단위행렬 : 대각선 상의 모든 원소가 1이고, 나머지 원소가 0)
#print(np.linalg.inv(d))
e = np.array([[1,2],[3,4]])
print(np.linalg.inv(e))


[[-2.   1. ]
 [ 1.5 -0.5]]


# 4. 순차적인 값 생성
NumPy에서 np.arange() 함수는 일정한 간격으로 숫자들을 생성하는 데 사용됩니다. 이 함수는 Python의 기본 range() 함수와 유사하지만, NumPy 배열을 반환하므로 수학적인 연산이 가능합니다.

In [ ]:
arr2 = np.arange(1, 11)
print(arr2)

for i in arr2:
    print(i, end=' ')

[ 1  2  3  4  5  6  7  8  9 10]
1 2 3 4 5 6 7 8 9 10 

# 5. 정렬

NumPy의 np.sort() 함수는 배열을 정렬하는 데 사용됩니다. 이 함수는 기본적으로 원래 배열을 변경하지 않고 정렬된 배열의 복사본을 반환합니다.

In [ ]:
ndarr1 = np.array([1, 10, 5, 7, 2, 4, 3, 6, 8, 9])
print(ndarr1)

[ 1 10  5  7  2  4  3  6  8  9]


In [ ]:
print(np.sort(ndarr1)) # 오름차순
print(ndarr1) # sort된채로 유지되지 않음(원본유지)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1 10  5  7  2  4  3  6  8  9]


In [ ]:
print(np.sort(ndarr1)[::-1]) # 슬라이싱을 활용한 내림차순

[10  9  8  7  6  5  4  3  2  1]


In [ ]:
ndarr2d = np.array([[11,10,12,9],
                    [3,1,4,2],
                    [5,6,7,8]])
print(ndarr2d.shape)

(3, 4)


In [ ]:
# 행정렬
print(ndarr2d)
print(np.sort(ndarr2d,axis=0)) # axis는 정렬기준할 행을 입력한다

[[11 10 12  9]
 [ 3  1  4  2]
 [ 5  6  7  8]]
[[ 3  1  4  2]
 [ 5  6  7  8]
 [11 10 12  9]]


In [ ]:
# 열정렬
print(ndarr2d)
print(np.sort(ndarr2d)) # 기본값: 열
print(np.sort(ndarr2d, axis=1))

[[11 10 12  9]
 [ 3  1  4  2]
 [ 5  6  7  8]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]
[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


In [ ]:
# 열정렬 내림차순
print(np.sort(ndarr2d, axis=1)[:,::-1])

[[12 11 10  9]
 [ 4  3  2  1]
 [ 8  7  6  5]]


In [ ]:
# 축의 마지막 방향으로 정렬
print(np.sort(ndarr2d, axis=-1))

[[ 9 10 11 12]
 [ 1  2  3  4]
 [ 5  6  7  8]]


### 99. 윤섭_개인필기

1.넘파이 : 큰 데이터셋에서 빠르게 수치연살 할때(c언어로 구현)

2. ndarray : 다차원배열(넘파이배열)

3. ndarray는 동일한 형태의 객체만 들어가야함(스트링 / 인티저)

4. 데이터타입변환_데이터의 크기순서:
불린 < 정수 < 실수 < 문자열